// Lightbox CSS
import "yet-another-react-lightbox/styles.css";
import "yet-another-react-lightbox/plugins/captions.css";
// react image crop
import "react-image-crop/dist/ReactCrop.css";
import "~/app/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ThemeProvider } from "@hktekno/ui/components/theme-provider";
import { Toaster } from "@hktekno/ui/components/ui/sonner";
import { TooltipProvider } from "@hktekno/ui/components/ui/tooltip";
import { cn } from "@hktekno/ui/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "weekcan",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={cn("", inter.className)}>
        <ThemeProvider disableTransitionOnChange attribute="class">
          <TooltipProvider delayDuration={300}>{children}</TooltipProvider>
        </ThemeProvider>
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
