import '@repo/ui/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ThemeProvider } from '@repo/ui/components/theme-provider';
import { Toaster } from '@repo/ui/components/ui/sonner';
import { cn } from '@repo/ui/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Docs',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('', inter.className)}>
        <ThemeProvider disableTransitionOnChange attribute="class">
          {children}
        </ThemeProvider>
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
